import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    CREATE TABLE marketing_scores (
      id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      image_id    UUID NOT NULL REFERENCES images(id) ON DELETE CASCADE,
      tag_slug    VARCHAR(150) NOT NULL,
      score       INTEGER NOT NULL CHECK (score >= 0 AND score <= 100),
      reasoning   TEXT,
      model       VARCHAR(100),
      cost_usd    DECIMAL(10, 6) DEFAULT 0,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    COMMENT ON TABLE marketing_scores IS 'Per-niche marketing relevance scores generated by LLMs';

    CREATE INDEX idx_marketing_scores_image_id ON marketing_scores (image_id);
    CREATE INDEX idx_marketing_scores_tag_slug ON marketing_scores (tag_slug);
    CREATE INDEX idx_marketing_scores_score ON marketing_scores (score DESC);

    CREATE TABLE marketing_score_progress (
      id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      tag_slug        VARCHAR(150) NOT NULL UNIQUE,
      total_images    INTEGER NOT NULL DEFAULT 0,
      processed       INTEGER NOT NULL DEFAULT 0,
      failed          INTEGER NOT NULL DEFAULT 0,
      status          VARCHAR(20) NOT NULL DEFAULT 'pending',
      started_at      TIMESTAMPTZ,
      completed_at    TIMESTAMPTZ,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    COMMENT ON TABLE marketing_score_progress IS 'Tracks batch marketing score generation progress per niche';

    CREATE INDEX idx_marketing_score_progress_tag_slug ON marketing_score_progress (tag_slug);
    CREATE INDEX idx_marketing_score_progress_status ON marketing_score_progress (status);
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`
    DROP TABLE IF EXISTS marketing_score_progress;
    DROP TABLE IF EXISTS marketing_scores;
  `);
}
